/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#5a4136",
        "on-primary-fixed-variant": "#7a3000",
        "on-tertiary-fixed": "#001d35",
        "surface-variant": "#353534",
        "error-container": "#93000a",
        "on-primary-container": "#572000",
        "on-tertiary-container": "#003357",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "surface-elevated": "#141414",
        "surface-dim": "#131313",
        "surface-tint": "#ffb693",
        "secondary-fixed": "#ffe170",
        "on-secondary-fixed": "#221b00",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#ffb693",
        "surface-container-low": "#1c1b1b",
        "on-secondary-container": "#6f5c00",
        "secondary": "#fff3d2",
        "surface-base": "#0A0A0A",
        "tertiary-fixed": "#d0e4ff",
        "text-high-contrast": "#FFFFFF",
        "surface-bright": "#3a3939",
        "surface": "#131313",
        "surface-container": "#201f1f",
        "on-surface-variant": "#e2bfb0",
        "tertiary": "#9ccaff",
        "on-error": "#690005",
        "on-primary": "#561f00",
        "on-error-container": "#ffdad6",
        "text-muted": "#A1A1AA",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#351000",
        "tertiary-fixed-dim": "#9ccaff",
        "outline": "#a98a7d",
        "secondary-fixed-dim": "#e9c400",
        "background": "#000000",
        "on-surface": "#e5e2e1",
        "on-secondary": "#3a3000",
        "inverse-on-surface": "#313030",
        "secondary-container": "#fdd400",
        "on-tertiary-fixed-variant": "#00497b",
        "border-subtle": "#262626",
        "primary": "#FF6B00",
        "primary-fixed": "#ffdbcc",
        "on-secondary-fixed-variant": "#544600",
        "on-tertiary": "#003257",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#a04100",
        "tertiary-container": "#059eff",
        "primary-container": "#FF6B00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "section-gap": "48px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "display-xl-mobile": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
